name: "Bug Report"
description: "Use this template to report bugs found during testing"
title: "[BUG] - "
labels: ["Bug", "rework"]
body:
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: Describe the bug and how it was found.
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List steps to reproduce the bug.
    validations:
      required: true

  - type: textarea
    id: testcase_ref
    attributes:
      label: Testcase Reference
      description: Link to failed testcase or test run log.
